
package employeemanagment.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://services.employeemanagment/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @param empId
     * @return
     *     returns employeemanagment.services.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeById", targetNamespace = "http://services.employeemanagment/", className = "employeemanagment.services.GetEmployeeById")
    @ResponseWrapper(localName = "getEmployeeByIdResponse", targetNamespace = "http://services.employeemanagment/", className = "employeemanagment.services.GetEmployeeByIdResponse")
    @Action(input = "http://services.employeemanagment/EmployeeService/getEmployeeByIdRequest", output = "http://services.employeemanagment/EmployeeService/getEmployeeByIdResponse")
    public Employee getEmployeeById(
        @WebParam(name = "empId", targetNamespace = "")
        String empId);

}
